baseURL = "http://demo.devcenter.bitrise.io.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
title = "Bitrise Devcenter"
theme = "hugo-material-docs"
[taxonomies]
tag = ""
group = ""
category = ""
[[menu.main]]
name = "Getting Started"
url = "/getting-started/"
weight = 1
