baseURL = "http://demo.devcenter.bitrise.io.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
theme = "hugo-material-docs"
title = "Bitrise Devcenter"
[[menu.main]]
name = "Getting Started"
url = "/getting-started/"
weight = 1
